server:
  port: 7001
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:ftpdb/remote.db
    username:
    password:
  devtools:
    livereload:
      enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.icbc.ftp.dao
download:
  path: D:\\icbc
